export const movieData=[
   {title:"The Exchange",
description:"Dans les années 80, deux femmes décident de conquérir la bourse koweïtienne, un univers impitoyable et corrompu jusque-là réservé aux hommes. Inspiré de faits réels.",
posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABcfJl4W-qDVnQDeLruS_K3m_fBuz1BcnrdWMZ-W1AlDoeHBP-NeuULsymFRE2FbGvH7_DVuPBe24OYFnvj3ZL_t1oHJo5pPQzCLEg9kEwqkEZff5rM-oGEpi-BQqbkW5TWsL.jpg?r=e1c",
rating:4,pub:0,
tadhmin:"https://www.youtube.com/embed/gTmkyFNKDiA",
   },
   {title:"Ola cherche sa voie",
   description:"Après un événement bouleversant, Ola part à la découverte d'elle-même tout en essayant d'élever deux enfants et de joindre les deux bouts.",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABYA0jnYL4B2IucWZw-NCZynuXt8rbKOpjcA1aYLeWvLobc_pNpcfSQr6MtSNW8PDz6ylrwBaf1mTLe2TYIDCDstYS0lJ6bjVKTBA27ERBgSA30Uhixk4NJLjq3T_IN5pdNwI.jpg?r=f3f",
   rating:4,pub:0,
   tadhmin:"https://www.youtube.com/embed/61TQIcoRB_4",}
   ,
   {title:"Ghodwa",
   description:"Alors que sa santé se dégrade et que son passé tumultueux revient le hanter, un Tunisien renoue avec son fils adolescent dont il s'était éloigné.",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABd9ybw3FrixXzJ-X61lSYjtNZ3B7FNmaRBhKvPL1AsjAY3cf6FW4SzPcBtdFZqJ6N-R4rSppGcUkjSoysJ__V108mkvCEhO80-8.jpg?r=847",
   rating:2,pub:0,
   tadhmin:"https://www.youtube.com/embed/yaTZomubGPc",}
   ,
   {title:"The Platform",
   description:"Un programmeur de génie met au point un portail Internet capable de récolter des indices conduisant à la vérité, tandis que la crise couve chez lui.",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABfdIM_VTzk-T6hBXSJcXa-DSBMuUtL_Q_uLjPtkSMuuGxaC-KqCFXaOPWNKI9ET1h8DjYPMZWKqQ1hQN211Ijxb30bFRBxjGgJI.jpg?r=cea",
   rating:4,pub:0,
tadhmin:"https://www.youtube.com/embed/bnGAgAgorC4",}
   ,
   {title:"Noura Rêve",
   description:"Lorsque son mari violent bénéficie d'une libération anticipée, une femme se bat pour sauver la nouvelle vie qu'elle avait imaginée avec son amant et ses trois enfants.",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABW4pSn4R-t0tCoZmnuKLV-UrsMGwVeslEQMDsY7TeYnW__BwBw8bRJJjsVPLm9vRVa2DXk209klVMjUuKpYVeGpGiWZm2WoKjgM.jpg?r=578",
   rating:3,pub:0,
   tadhmin:"https://www.youtube.com/embed/dCxb1sFrJ28",}
   ,
   {title:"Le Destin",
   description:"Au 12e siècle, dans une Espagne sous domination arabe, les enseignements d'un penseur ébranlent le pouvoir du calife en place, que ses opposants menacent de renverser",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABXmrDqDMeYzSy6m8MmyhuZawFQujGAiYtT-zZvwcbQP0qp39LFLDPaOacl-G3rhYcfHIv3O3HgL8bQTzxmg6mL47dG0el2wbz1c.jpg?r=46e",
   rating:5,
   pub:2,
   tadhmin:"https://www.youtube.com/embed/lusJxBk8ha4",}
   ,
   {title:"Né en Syrie",
   description:"Ce documentaire intimiste suit un groupe d'enfants syriens, venus se réfugier dans un pays étranger pour échapper à une vie de misère et de tourments.",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABfzMBcEQPL-I66zZvZnV3RsR0Vj548sNIa-763FIjBGRAA3riffd24N9QNCK5SOI28xcorg5Tn0PSw8CGRZLcL5BWcdPI_hnvFU.jpg?r=489",
   rating:3,
pub:1,
tadhmin:"https://www.youtube.com/embed/-4HijoCgnXY",}
   ,
   {title:"Children of Shatila",
   description:"Cinquante ans après l'exil de leurs grands-parents palestiniens, deux enfants du camp de réfugiés de Chatila à Beyrouth recueillent des témoignages de perte et de guerre.",
   posterURL:"https://occ-0-4609-3933.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABWU5zERAu7jjYOmNJpOnJgseFivQlysyVIShp0nZti1JWvdHCaihRsAeTXhqlVR41eE3IFo3dHEDrWplA34EYitOuXzIo48ZKzA.jpg?r=c4c",
   rating:5,
pub:3,
tadhmin:"https://www.youtube.com/embed/SXSmbXBUIhk",}]
